src/WesternApparel/Controllers/CartController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WesternApparel.Core.Cart;

namespace WesternApparel.Controllers
{
    [Authorize]
    [Route( "[controller]" )]
    public class CartController : Controller
    {
        readonly ICartService _cartService;

        public CartController( ICartService cartService )
        {
            _cartService = cartService;
        }

        [HttpGet]
        public async Task<ViewResult> CartView( )
        {
            var user = User.GetSystemUserOrThrow( );
            
            return View( new CartViewModel
            {
                Cart = await _cartService.GetCartAsync( user.ID )
            } );
        }

        [HttpGet("[action]")]
        public async Task<RedirectToActionResult> RemoveCartItem( Guid cartItemID )
        {
            var user = User.GetSystemUserOrThrow(  );
            
            await _cartService.RemoveItemFromCartAsync( user.ID, cartItemID );

            return RedirectToAction( "CartView" );
        }
    }
}

src/WesternApparel/Controllers/CatalogController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using WesternApparel.Core.Catalog;

namespace WesternApparel.Controllers
{
    [Route( "shop/[controller]" )]
    public class CatalogController : Controller
    {
        readonly ICatalogRepository _catalogRepository;

        public CatalogController( ICatalogRepository catalogRepository )
        {
            this._catalogRepository = catalogRepository;
        }

        [HttpGet("{Category?}")]
        public async Task<ViewResult> BrowseView( BrowseViewRequest request = null )
        {
            if( request is not null && request.Category != null )
                request.Category = request.Category.Replace( "%2F", "/", StringComparison.OrdinalIgnoreCase );
            
            var vm = await _catalogRepository.FetchBrowsePageProductsAsync( new BrowseViewRequest
            {
                Category = request?.Category, 
                PageSize = 24, 
                Page = request?.Page ?? 1
            });

            vm.Category = request?.Category;

            return View( vm );
        }
    }
}

src/WesternApparel/Controllers/CheckoutController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WesternApparel.Core.Cart;
using WesternApparel.Core.Checkout;

namespace WesternApparel.Controllers
{
    [Authorize]
    [Route( "[controller]" )]
    public class CheckoutController : Controller
    {
        readonly ICartService _cartService;

        public CheckoutController( ICartService cartService )
        {
            _cartService = cartService;
        }

        [HttpGet]
        public async Task<ViewResult> CheckoutView( [FromForm] AddToCartRequest request = null )
        {
            var user = HttpContext.User.GetSystemUser( );
            var userCart = await _cartService.GetCartAsync( user.ID );
            
            var vm = new CheckoutViewModel
            {
                Title = "Checkout",
                CartItems = userCart?.CartItems
            };

            return View( vm );
        }
    }
}

src/WesternApparel/Controllers/ProductController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WesternApparel.Core.Cart;
using WesternApparel.Core.Product;

namespace WesternApparel.Controllers
{
    [Route( "shop/[controller]" )]
    public class ProductController : Controller
    {
        readonly IProductRepository _productRepository;
        readonly ICartService _cartService;

        public ProductController( IProductRepository productRepository, ICartService cartService )
        {
            this._productRepository = productRepository;
            this._cartService = cartService;
        }

        [HttpGet("{id}")]
        public async Task<ViewResult> ProductView( int id )
        {
            var vm = await _productRepository.FetchProductPageDataAsync( id );
            vm.CartFormItem = new AddToCartRequest
            {
                ProductID = id,
                Quantity = 1,
                IsGiftItem = false
            };

            return View( "ProductView", vm );
        }

        [HttpPost("{id?}")]
        public async Task<IActionResult> AddToCart( [FromForm(Name = "CartFormItem")] AddToCartRequest request )
        {
            if( !ModelState.IsValid )
                return await ProductView( request.ProductID );
            
            var user = HttpContext.User.GetSystemUser( );

            var newCartItem = await _productRepository.FillCartItemInfo( request.ProductID );
            if( newCartItem is not null )
            {
                newCartItem.Quantity = request.Quantity;
                newCartItem.IsGiftItem = request.IsGiftItem;

                await _cartService.AddItemToCartAsync( user.ID, newCartItem );
            }
            else
            {
                // TODO: Should do something to let the user know the cart item was not successfully added
            }

            return RedirectToAction( "CartView", "Cart" );
        }
    }
}

src/WesternApparel/Views/Checkout/CheckoutView.cshtml
@using WesternApparel.Core.Cart
@model WesternApparel.Core.Checkout.CheckoutViewModel
@{
    Layout = "SiteLayout";

    string FormatCheckoutPrice( CartItem cartItem )
    {
        if( cartItem.Quantity <= 1 )
        {
            return $"{cartItem.UnitProductPriceUSD.ToString( "C" )}";
        }
        else
        {
            return $"{cartItem.Quantity} x {cartItem.UnitProductPriceUSD.ToString( "C" )}";
        }
    }
}

<div class="container">
<div class="py-4 text-center">
    <h2>Checkout</h2>
  </div>
<div class="row">
    <div class="col-md-4 order-md-2 mb-4">
        <h4 class="d-flex justify-content-between align-items-center mb-0">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">@(Model.CartItems?.Sum(i => i.Quantity) ?? 0)</span>
        </h4>
        <a asp-controller="Cart" asp-action="CartView" class="d-block small mb-3">Edit</a>
        <ul class="list-group mb-3">
            @if( Model.CartItems?.Count > 0 )
            {
                foreach( var cartItem in Model.CartItems )
                {
                    <li class="list-group-item d-flex justify-content-between lh-condensed">
                        <a asp-controller="Product" asp-action="ProductView" asp-route-id="@cartItem.ProductID" class="d-block text-dark text-decoration-none">
                            <h6 class="my-0">@cartItem.ProductName</h6>
                            @if( cartItem.IsGiftItem ) {
                                <small class="text-muted has-tooltip" data-placement="bottom" title="The item will be shipped in packaging that does not reveal it's contents.">This item is a gift</small>
                            }
                        </a>
                        <span class="text-muted ml-1">@FormatCheckoutPrice(cartItem)</span> @* Obvious TODO: consider other cultures / currencies *@
                    </li>
                }
            @* <li class="list-group-item d-flex justify-content-between bg-light"> *@
            @*     <div class="text-success"> *@
            @*         <h6 class="my-0">Promo code</h6> *@
            @*         <small>EXAMPLECODE</small> *@
            @*     </div> *@
            @*     <span class="text-success">-$5</span> *@
            @* </li> *@
                <li class="list-group-item d-flex justify-content-between">
                    <u>Total (USD)</u>
                    <strong>@Model.CartItems.Sum( i => i.UnitProductPriceUSD * i.Quantity ).ToString("C")</strong>
                </li>
            }
            else
            {
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                    <div>
                        <h6 class="my-0">No items in cart</h6>
                        <small class="text-muted">Please browse our <a asp-controller="Catalog" asp-action="BrowseView">catalog</a></small>
                    </div>
                </li>
                <li class="list-group-item d-flex justify-content-between">
                    <u>Total (USD)</u>
                    <strong>$0</strong>
                </li>
            }
        </ul>

    </div>
    <div class="col-md-8 order-md-1">
        <h4 class="mb-3">Billing address</h4>
        <span class="text-muted d-block mb-3">WARNING: Please do not enter any real or private information. Clicking purchase below will <u>NOT</u> charge any accounts, and any information entered will <u>NOT</u> be stored anywhere. This site is intended only for demonstration.</span>
        <form class="needs-validation" novalidate="">
            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="firstName">First name</label>
                    <input type="text" class="form-control" id="firstName" placeholder="" value="" required="">
                    <div class="invalid-feedback">
                        Valid first name is required.
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="lastName">Last name</label>
                    <input type="text" class="form-control" id="lastName" placeholder="" value="" required="">
                    <div class="invalid-feedback">
                        Valid last name is required.
                    </div>
                </div>
            </div>

            <div class="mb-3">
                <label for="address">Address</label>
                <input type="text" class="form-control" id="address" placeholder="1234 Main St" required="">
                <div class="invalid-feedback">
                    Please enter your shipping address.
                </div>
            </div>

            <div class="mb-3">
                <label for="address2">Address 2 <span class="text-muted">(Optional)</span></label>
                <input type="text" class="form-control" id="address2" placeholder="Apartment or suite">
            </div>

            <div class="row">
                <div class="col-md-5 mb-3">
                    <label for="country">Country</label>
                    <select class="custom-select d-block w-100" id="country" required="">
                        <option value="">Choose...</option>
                        <option>United States</option>
                    </select>
                    <div class="invalid-feedback">
                        Please select a valid country.
                    </div>
                </div>
                <div class="col-md-4 mb-3">
                    <label for="state">State</label>
                    <select class="custom-select d-block w-100" id="state" required="">
                        <option value="">Choose...</option>
                        <option>California</option>
                    </select>
                    <div class="invalid-feedback">
                        Please provide a valid state.
                    </div>
                </div>
                <div class="col-md-3 mb-3">
                    <label for="zip">Zip</label>
                    <input type="text" class="form-control" id="zip" placeholder="" required="">
                    <div class="invalid-feedback">
                        Zip code required.
                    </div>
                </div>
            </div>
            <hr class="mb-4">

            <h4 class="mb-3">Payment</h4>

            <div class="d-block my-3">
                <div class="custom-control custom-radio">
                    <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" checked="" required="">
                    <label class="custom-control-label" for="credit">Credit card</label>
                </div>
                <div class="custom-control custom-radio">
                    <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" required="" disabled>
                    <label class="custom-control-label" for="debit">Debit card</label>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="cc-name">Name on card</label>
                    <input type="text" class="form-control" id="cc-name" placeholder="" required="">
                    <small class="text-muted">Full name as displayed on card</small>
                    <div class="invalid-feedback">
                        Name on card is required
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <label for="cc-number">Credit card number</label>
                    <input type="text" class="form-control" id="cc-number" placeholder="" required="">
                    <div class="invalid-feedback">
                        Credit card number is required
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3 mb-3">
                    <label for="cc-expiration">Expiration</label>
                    <input type="text" class="form-control" id="cc-expiration" placeholder="" required="">
                    <div class="invalid-feedback">
                        Expiration date required
                    </div>
                </div>
                <div class="col-md-3 mb-3">
                    <label for="cc-cvv">CVV</label>
                    <input type="text" class="form-control" id="cc-cvv" placeholder="" required="">
                    <div class="invalid-feedback">
                        Security code required
                    </div>
                </div>
            </div>
            <hr class="mb-4">
            <span class="d-block mb-4 text-muted">By clicking purchase you agree to [POLICYHERE]. </span>
            <button class="btn btn-primary btn-lg btn-block" type="submit">Make Purchase</button>
        </form>
    </div>
</div>
</div>