src/WesternApparel/Controllers/CartController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WesternApparel.Core.Cart;

namespace WesternApparel.Controllers
{
    [Authorize]
    [Route( "[controller]" )]
    public class CartController : Controller
    {
        readonly ICartService _cartService;

        public CartController( ICartService cartService )
        {
            _cartService = cartService;
        }

        [HttpGet]
        public async Task<ViewResult> CartView( )
        {
            var user = User.GetSystemUserOrThrow( );
            
            return View( new CartViewModel
            {
                Cart = await _cartService.GetCartAsync( user.ID )
            } );
        }

        [HttpGet("[action]")]
        public async Task<RedirectToActionResult> RemoveCartItem( Guid cartItemID )
        {
            var user = User.GetSystemUserOrThrow(  );
            
            await _cartService.RemoveItemFromCartAsync( user.ID, cartItemID );

            return RedirectToAction( "CartView" );
        }
    }
}

src/WesternApparel/Controllers/CatalogController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using WesternApparel.Core.Catalog;

namespace WesternApparel.Controllers
{
    [Route( "shop/[controller]" )]
    public class CatalogController : Controller
    {
        readonly ICatalogRepository _catalogRepository;

        public CatalogController( ICatalogRepository catalogRepository )
        {
            this._catalogRepository = catalogRepository;
        }

        [HttpGet("{Category?}")]
        public async Task<ViewResult> BrowseView( BrowseViewRequest request = null )
        {
            if( request is not null && request.Category != null )
                request.Category = request.Category.Replace( "%2F", "/", StringComparison.OrdinalIgnoreCase );
            
            var vm = await _catalogRepository.FetchBrowsePageProductsAsync( new BrowseViewRequest
            {
                Category = request?.Category, 
                PageSize = 24, 
                Page = request?.Page ?? 1
            });

            vm.Category = request?.Category;

            return View( vm );
        }
    }
}

src/WesternApparel/Views/Shared/BaseLayout.cshtml
@using Microsoft.AspNetCore.Mvc.ModelBinding
@using System.Text
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="~/" />
    <title>@Model.Title - Western Apparel</title>
    <link rel="stylesheet" href="~/styles/site.css" />
    @RenderSection( "Styles", required: false )
</head>
<body>
    <div id="page" class="min-vh-100">
        @RenderBody( )
    </div>
    <script src="~/lib/jquery-3.5.1.slim.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap-4.5.0/js/bootstrap.bundle.min.js"></script>
    @RenderSection( "Scripts", required: false )
    @* This will be moved into a scripts.js at some point *@
    <script>
        @* This obviously will not *@ 
        var serverSideValidationErrors = [
            @Html.Raw( GenerateModelStateErrorElements() )
        ];
    
        function displayErrorTooltip( err ) {
            $( err.element )
                .attr('title', err.message)
                .attr('data-original-title', err.message)
                .tooltip( 'update' ).tooltip( 'show' );
            
            $( err.element ).focus(); // Make sure at least one of the error fields are focused on load
        }
        
        $(function () {
            $('.has-tooltip').tooltip();
            $('.tooltip-auto').tooltip('show'); @* Items with this class will have their tooltip visible automatically *@
            
            $("form").bind("invalid-form.validate", function(event, validator) {
                validator.errorList.forEach( displayErrorTooltip );
            });
            
            serverSideValidationErrors.forEach( displayErrorTooltip );
        });
            
    </script>
</body>
</html>

@functions {

    string GenerateModelStateErrorElements( )
    {
        StringBuilder sb = new StringBuilder( );

        foreach( var (key, state) in ViewData.ModelState )
        {
            if( state.ValidationState != ModelValidationState.Invalid )
                continue;

            var errorMessage = state.Errors.FirstOrDefault( )?.ErrorMessage;
            if( string.IsNullOrWhiteSpace( errorMessage ) )
                continue;
            
            sb.Append( "{ element: 'input[name=" );
            sb.Append( key );
            sb.Append( "]', message: '" );
            sb.Append( errorMessage );
            sb.Append( "' }, \n" );
        }

        return sb.ToString( );
    }

}

src/WesternApparel/Views/Shared/CategoryCrumbs.cshtml
@using System.Text
@model string

@{
    StringBuilder currentPath = new StringBuilder( );
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Catalog" asp-action="BrowseView" asp-route-Category="" title="Return to catalog">catalog</a></li>
        @foreach( var crumb in Model.Split( "/" ) )
        {
            currentPath.Append( crumb );
            <li class="breadcrumb-item"><a asp-controller="Catalog" asp-action="BrowseView" asp-route-Category="@currentPath.ToString()" title="See more @crumb">@crumb</a></li>
            currentPath.Append( '/' );
        }
    </ol>
</nav>

src/WesternApparel/Views/Shared/SiteFooter.cshtml
<footer class="border-top footer text-muted">
    <div class="container d-flex justify-content-between p-2">
        <span>
            Western Apparel - Jonathan Acampora &copy; 2020 - <u>ALL RIGHTS RESERVED</u>
        </span>
        <span class="text-right">
            THIS SITE IS DEMONSTRATIONAL, NO GOODS OR SERVICES WILL BE EXCHANGED
        </span>
    </div>
</footer>

src/WesternApparel/Views/Shared/SiteLayout.cshtml
@{ Layout = "BaseLayout"; }

@section Styles {
    @RenderSection( "Styles", false )
}
@section Scripts {
    @RenderSection( "Scripts", false )
}

<div id="page" style="grid-template-rows: auto 100fr auto">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark shadow-sm">
            <div class="container">
                <a class="navbar-brand" asp-controller="Landing" asp-action="LandingView">Western Apparel</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Catalog" asp-action="BrowseView">Shop</a>
                        </li>
                    </ul>
                    @if( User.Identity?.IsAuthenticated is true )
                    {
                        <div class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="text-light">Hello, </span>@User.Identity.Name
                            </a>
                            <div class="dropdown-menu" aria-labelledby="userDropdownMenuLink">
                                <a class="dropdown-item" asp-controller="Cart" asp-action="CartView">My Cart</a>
                                <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Logout</a>
                            </div>
                        </div>
                    }
                    else
                    {
                        <a asp-controller="Account" asp-action="Login" class="btn btn-primary font-weight-bold">Sign In</a>
                    }
                </div>

            </div>
        </nav>
    </header>

    <main role="main" class="pb-3">
        @RenderBody( )

    </main>
    
    <partial name="SiteFooter" />
</div>